#+title: Research
#+author: Vu Huy Minh Pham
* Resources
** Photogammetry High Level Overview
*** Motivation
In big games, you have actors which are scanned and put in the game environment. What if indie developers can do this inexpensively? Small university game development teams would be very interested in this.

Personally, it's a good resume project for companies like polycam, arctec3d, etc.
*** [[https://www.artec3d.com/learning-center/what-is-photogrammetry][What is photogammetry?]]
**** Definitions and Goal
Photogammetry can be defined as taking reliable measurements from photographs. Understanding real world geometry from one single perspective (one single photo) with just a ruler is a naive method for photogammetry, as such the solution is to just take multiple photos of an object. As part of our goal to construct a 3d model, we need to make inferences about he dimensions and physical properties of objects. The goal of this repository is to write a software that interpret spatial information and render out geometry.
***** Triangulation
Triangulation is the process of identifying the same points in multiple images and taking into account parameters: camera's position and orientation for each photograph, its focal length, lens distortion, and other variables. Then we can infer where those points were located in 3D space.
****** General Method
We draw imaginary lines from two or more camera positions in the direction of that point. We mathematically determine where the lines intersect. The converging lines give us the XYZ coordinates of the targeted point. With enough points, we construct a model of the scene.
****** Missing Inference - Scale
The one single missing inference is scale. Photogammetry only provides proportion. Scale is important in metric photogammetry
***** Photogammetry for Engineering vs. 3D modeling
Metric photogammetry requires scale (inputs needing a frame of reference). 3D-Model photogammetry requires as much pixels and points as possible, demanding life-like renders of real-world objects sacrificing accuracy for noise. The latter is what I'm interested in. But undoubtedly, with enough time I could try to write both.
***** Hardware Required
It looks like a camera, calibrated scale bars, a set of targets are the essentials.
**** General Task List For Software
1. Understanding the math behind interpeting photos of multiple perspectives
2. With this understanding convert spatial information into a 3d file, possibly an obj blender file.
3. At this point, we could use blender to view our file. And if I am really enthusiastic and very unlikely write a 3d model viewer later on using SDL3.
***** Procuring Inputs
We need to procure the images as per the photogammetry methods like [[Triangulation]].
** Algorithm Overview
*** [[https://khanhha.github.io/portfolio/photogrammetry-algorithms/][Fundamental Photogammetry]]
Purpose: this blog post is from Khanh Ha. I just want to know what has to be done to achhieve the most basic tasks in photogammetry.
**** Math Homography
This is defined as a mathematical transformation used in computer vision and geometry to map the points of one flat surface to the corresponding points in another.

What does this sound like? Picture stitching, panorama.
This could be an essential sub-project.
**** Correspondence Analysis
A multivariate statistical technique that transforms complex, large categorical data tables into simple, intutive visual maps.
**** Direct Linear Transformation (DLT)
In Ha's experiment, he usesd this for camera calibration. Direct lienar transformation algorithm is used to estimate the intrinsic and extrinsic camera parameters using correspondences between 3D-2D control points.
**** Epipolar Constraint
A foundational rule in computer vision and multi-view geometry.
** [[https://visionbook.mit.edu/][MIT VisionBook Notes]]
:PROPERTIES:
:ID:       117aa5a7-5dfb-48e8-8ab7-097361149743
:END:
*** Regarding Changes in the Field of Computer Vision
The primary catalyst that was talked about during the preface was the 2012 revolution of deep learning as a tool for computer vision.

A big challenge as a new learner and writer of any book about computer vision are approaches of the past that are now dethroned by the newer methods. The authors of the book promised that many of these approaches could be categorized in overarching ideas. Hence like many other fields computer vision have foundational concepts that are foundational.



